export const jobData = [
  {
    title: "UI/UX Assistant Manager",
    company: "VAYUZ",
    category: "Designer",
    location: "India",
    salary: "25,000 Rupees P.M.",
    city: "Noida",
    experience: "2 years",
    applicants: "120 Applicants",
    views: "4k Viewed",
    postedAt: "15h",
  },
  {
    title: "UI/UX Designer",
    company: "CreativeWorks",
    location: "USA",
    salary: "50,000 USD",
    city: "New York",
    experience: "3 years",
    applicants: "80 Applicants",
    views: "3.5k Viewed",
    postedAt: "1d",
    category: "Designer",
  },
  {
    title: "Figma",
    company: "CreativeWorks",
    location: "USA",
    salary: "50,000 USD",
    city: "New York",
    experience: "3 years",
    applicants: "80 Applicants",
    views: "3.5k Viewed",
    postedAt: "1d",
    category: "Designer",
  },
  {
    title: "Graphic Designer",
    company: "DesignHub",
    location: "Canada",
    salary: "40,000 CAD",
    city: "Vancouver",
    experience: "2 years",
    applicants: "60 Applicants",
    views: "2.8k Viewed",
    postedAt: "2d",
    category: "Designer",
  },
  {
    title: "Web Developer",
    company: "TechSolutions",
    location: "India",
    salary: "55,000 Rupees P.M.",
    city: "Bangalore",
    experience: "4 years",
    applicants: "100 Applicants",
    views: "4.2k Viewed",
    postedAt: "1h",
    category: "Web Developers",
  },
  {
    title: "Frontend Developer",
    company: "CodeCrafters",
    location: "Germany",
    salary: "60,000 EUR",
    city: "Berlin",
    experience: "3 years",
    applicants: "90 Applicants",
    views: "3.8k Viewed",
    postedAt: "15h",
    category: "Web Developers",
  },
  {
    title: "Mobile App Developer",
    company: "AppMasters",
    location: "Singapore",
    salary: "65,000 SGD",
    city: "Singapore",
    experience: "5 years",
    applicants: "120 Applicants",
    views: "4.5k Viewed",
    postedAt: "2d",
    category: "Mobile Developers",
  },
  {
    title: "iOS Developer",
    company: "SwiftTech",
    location: "USA",
    salary: "70,000 USD",
    city: "San Francisco",
    experience: "4 years",
    applicants: "110 Applicants",
    views: "4.7k Viewed",
    postedAt: "1d",
    category: "Mobile Developers",
  },
  {
    title: "Marketing Specialist",
    company: "GlobalTech",
    location: "India",
    salary: "45,000 Rupees P.M.",
    city: "Mumbai",
    experience: "3 years",
    applicants: "70 Applicants",
    views: "3.3k Viewed",
    postedAt: "1h",
    category: "Marketing",
  },
  {
    title: "Digital Marketing Manager",
    company: "DigitalStrategies",
    location: "Canada",
    salary: "55,000 CAD",
    city: "Toronto",
    experience: "5 years",
    applicants: "130 Applicants",
    views: "5k Viewed",
    postedAt: "1d",
    category: "Marketing",
  },
  {
    title: "HR Specialist",
    company: "TalentHub",
    location: "Germany",
    salary: "50,000 EUR",
    city: "Munich",
    experience: "4 years",
    applicants: "90 Applicants",
    views: "4.2k Viewed",
    postedAt: "15h",
    category: "Human Resources",
  },
  {
    title: "Recruitment Manager",
    company: "HirePro",
    location: "Singapore",
    salary: "60,000 SGD",
    city: "Singapore",
    experience: "6 years",
    applicants: "150 Applicants",
    views: "5.5k Viewed",
    postedAt: "2d",
    category: "Human Resources",
  },
];
